Correct the Pipfile content and update packages
- We added only the necessary packages in the Pipfile
(there were more packages added there by mistake).

We had to pin the flake8 package because of the
following error when installing the packages:
ERROR: Cannot install -r /home/user/dev/grades-report/dev-requirements.txt (line 6),
-r /home/user/dev/grades-report/requirements.txt (line 2) and importlib-metadata==4.12.0
because these package versions have conflicting dependencies.

This seems to be related to https://github.com/pypa/pipenv/issues/4476.

- Added an option in the Makefile to create the
latest requirements files with the latest available
package versions.